version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'sampledb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mysql-admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  mysqlinit:
    image: mysql:latest
    volumes:
     - ./sampledb-scripts/:/dump/sql/
 
    #command: bash -c "sleep 20 && mysql -h db -uroot -ppassword sampledb < /dump/sql/employees.sql"
     
# Names our volume
volumes:
  my-db: